name: barnostri_app
description: "A Moninhay project"
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  cached_network_image: ^3.0.0
  intl: ^0.19.0
  qr_code_scanner: ^1.0.0
  image_picker: '>=1.1.2'
  supabase_flutter: '>=1.10.0'
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.0
  fl_chart: 0.68.0
  google_fonts: 6.1.0
  shared_preferences: 2.3.2
  path_provider: 2.1.4
  http: '>=1.0.0'
  uuid: '>=3.0.0'
  flutter_riverpod: ^2.4.0
  go_router: ^13.2.0
  shared_models:
    path: ../../packages/shared_models

dev_dependencies:
  flutter_test:
    sdk: flutter
  change_app_package_name: ^1.4.0
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  generate: true
  assets:
    - supabase/supabase-config.json
