name: barnostri_app
description: "A Moninhay project"
publish_to: 'none'
version: 1.0.0

environment:
  # Compatível com o SDK fornecido no ambiente do Codex
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter    # puxa intl 0.20.2
  # Se você realmente usa Intl diretamente, deixe esta linha
  intl: ">=0.18.1 <0.21.0"

  supabase_flutter: ^2.8.4        # compatível com o SDK usado nos testes
  cached_network_image: ^3.3.0
  qr_code_scanner:
    path: ../../packages/qr_code_scanner
  image_picker: ^1.0.7
  cupertino_icons: ^1.0.0
  fl_chart: ^0.63.0
  google_fonts: ^5.1.0
  shared_preferences: ^2.2.2
  path_provider: ^2.1.3
  http: '>=1.0.0'
  uuid: '>=3.0.0'
  flutter_riverpod: ^2.4.0
  go_router: ^13.0.0
  shared_models:
    path: ../../packages/shared_models

dev_dependencies:
  flutter_test:
    sdk: flutter
  change_app_package_name: ^1.4.0
  flutter_lints: ^4.0.0
  integration_test:
    sdk: flutter
  golden_toolkit: ^0.15.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - supabase/supabase-config.json
