name: shared_models
description: Shared data models and services for the Barnostri apps
version: 0.0.1
publish_to: 'none'

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.17.0
  supabase_flutter: ^2.9.1

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

