name: shared_models
description: Shared data models and services for the Barnostri apps
version: 0.0.1
publish_to: 'none'

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.17.0
  supabase_flutter: ^2.9.1
  flutter_riverpod: ^2.4.0

dev_dependencies:
  flutter_lints: ^6.0.0
  test: ^1.24.0
