name: shared_models
description: Shared data models and services for the Barnostri apps
version: 0.0.1
publish_to: 'none'

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.17.0
  supabase_flutter: ^2.8.4
  intl: ">=0.18.1 <0.21.0"

dev_dependencies:
  flutter_lints: ^4.0.0
  test: ^1.24.0
