name: Flutter CI

on:
  push:
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      # Get dependencies for both packages
      - run: flutter pub get
        working-directory: apps/barnostri_app

      - run: flutter pub get
        working-directory: packages/shared_models

      # Format both projects
      # - run: dart format --set-exit-if-changed .
      #   working-directory: apps/barnostri_app

      # - run: dart format --set-exit-if-changed .
      #   working-directory: packages/shared_models

      # Analyze both projects
      - run: flutter analyze
        working-directory: apps/barnostri_app

      - run: flutter analyze
        working-directory: packages/shared_models

      # Test both projects
      - run: flutter test
        working-directory: apps/barnostri_app

      - run: flutter test
        working-directory: packages/shared_models

  build:
    needs: tests
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - run: flutter pub get
        working-directory: apps/barnostri_app

      - run: flutter build web --release
        working-directory: apps/barnostri_app

      # - uses: w9jds/firebase-action@v2
      #   with:
      #     args: deploy --only hosting
      #   env:
      #     FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
